version: '3.8'

services:
  debug-aris-ai-mysql:
    image: mysql:latest
    container_name: debug-aris-ai-mysql
    privileged: true
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 5s
      retries: 10
    env_file:
      - ../../envs/local/mysql.env
  debug-aris-ai-redis:
    image: bitnami/redis:latest
    container_name: debug-aris-ai-redis
    privileged: true
    pid: host
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - ../../confs/local/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep PONG" ]
      interval: 5s
      retries: 10
    env_file:
      - ../../envs/local/redis.env

  debug-aris-ai-neo4j:
    image: neo4j:latest
    container_name: debug-aris-ai-neo4j
    privileged: true
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:7474/ || exit 1" ]
      interval: 5s
      retries: 10
    env_file:
      - ../../envs/local/neo4j.env

volumes:
  mysql-data:
    name: mysql-data
    external: true
  redis-data:
    name: redis-data
    external: true
  neo4j-data:
    name: neo4j-data
    external: true

# docker-compose -f docker/local/docker-compose.yml up -d --no-build