version: '3.8'

services:
  aris-ai-api:
    image: ghcr.io/hcd233/aris-ai:latest
    container_name: aris-ai-api
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../log:/data/log
    ports:
      - 8080:8080
    env_file:
      - ../../envs/deployment/api.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://aris-ai-api:8080/root/"]
      interval: 10s
      timeout: 5s
      retries: 2
    entrypoint: [
      "python", "aris_api.py",
    ]
    depends_on:
      aris-ai-mysql:
        condition: service_healthy

  aris-ai-webui:
    image: ghcr.io/hcd233/aris-ai:latest
    container_name: aris-ai-webui
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    env_file:
      - ../../envs/deployment/webui.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://aris-ai-webui:8501"]
      interval: 10s
      timeout: 5s
      retries: 2
    entrypoint: [
      "streamlit", "run", 
      "aris_webui.py",
      "--client.showSidebarNavigation", "false",
      "--runner.magicEnabled", "false",
      "--browser.gatherUsageStats", "false",
      "--server.maxUploadSize", "100",
    ]
    depends_on:
      aris-ai-api:
        condition: service_healthy    

  aris-ai-mysql:
    image: mysql:latest
    container_name: aris-ai-mysql
    privileged: true
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h aris-ai-mysql -P 3306 -u$$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 5s
      retries: 10
    env_file:
      - ../../envs/deployment/mysql.env

  aris-ai-redis:
    image: bitnami/redis:latest
    container_name: aris-ai-redis
    privileged: true
    volumes:
      - redis-data:/data
      - ../../confs/deployment/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep PONG" ]
      interval: 5s
      retries: 10
    env_file:
      - ../../envs/deployment/redis.env

volumes:
  mysql-data:
    name: mysql-data
    external: true
  redis-data:
    name: redis-data
    external: true

# docker-compose -f docker/deployment/docker-compose.yml up -d --no-build